-include .env

.PHONY: install

install:
	forge install https://github.com/huff-language/foundry-huff --no-commit
	forge install https://github.com/huff-language/huffmate --no-commit
	forge install openzeppelin/openzeppelin-contracts --no-commit 