[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    # "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]

# [dependencies]
# chainlink = { git = "https://github.com/smartcontractkit/chainlink.git", tag = "v0.8" }
# openzeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v4.8" }


[fuzz]
runs = 1000

[invariant]
runs = 100
depth = 100
fail_on_revert = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
