-include .env

.PHONY: install build

install :; forge install openzeppelin/openzeppelin-contracts --no-commit && forge install smartcontractkit/chainlink-brownie-contracts --no-commit && forge install openzeppelin/openzeppelin-foundry-upgrades --no-commit && forge install openzeppelin/openzeppelin-contracts-upgradeable --no-commit && forge install transmissions11/solmate --no-commit
