-include .env

.PHONY: install 

install:
	forge install https://github.com/Cyfrin/foundry-era-contracts.git --no-commit 
	forge install https://github.com/OpenZeppelin/openzeppelin-contracts.git --no-commit 
	forge install https://github.com/eth-infinitism/account-abstraction.git --no-commit
	forge install https://github.com/foundry-rs/forge-std.git --no-commit