-include .env

.PHONY: install

install:
	forge install openzeppelin/openzeppelin-contracts --no-commit
	forge install https://github.com/smartcontractkit/ccip@v2.17.0-ccip1.5.16 --no-commit
	forge install smartcontractkit/chainlink-local@7d8b2f888e1f10c8841ccd9e0f4af0f5baf11dab --no-commit
	forge install openzeppelin/openzeppelin-contracts --no-commit 
